package com.example.accessingdatarest.Controller;

import com.example.accessingdatarest.Model.Hystory;
import com.example.accessingdatarest.Repositories.HystoryRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.ArrayList;

@Controller // This means that this class is a Controller
@RequestMapping(path="/hystory") // This means URL's start with /demo (after Application path)
public class HystoryController {


    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private HystoryRepository hystoryRepository;

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Hystory> all() {
        // This returns a JSON or XML with the users
        Iterable<Hystory> all= hystoryRepository.findAll();
        for (var item:
             all) {System.out.println(item);

        }
        return all;
    }
}
